### ISSUE TITLE
Unable to include this component into Harmony 3

### ISSUE THREAD

**Issue by Maldus512** [Microchip-MPLAB-Harmony/bootloader#1]
To whomever (if any) may concern,
I am trying to explore bootloading solution on a PIC32MZ Graphics starter kit, sporting a PIC32MZ2064DAG169 device. After downloading the required dependencies for the Harmony framework I am unable to include the bootloader component into my project: trying to do so results in the following error being printed:

```
<Configuration Database>[Error]: Failed to activate component: bootloader
<Log>[Error]: Exception cause: Traceback (most recent call last):
  File "C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py", line 208, in instantiateComponent
    setupCoreComponentSymbols()
  File "C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py", line 184, in setupCoreComponentSymbols
    coreComponent.getSymbolByID("systickEnable").setValue(True)
	at com.microchip.h3.database.scriptinterface.component.ComponentRemoteSymbolInterface.getSymbolByID(ComponentRemoteSymbolInterface.java:22)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)


java.lang.NullPointerException: java.lang.NullPointerException
<Log>[Error]: Stack trace:
<Log>[Error]: org.python.core.Py.JavaError(Py.java:546)
<Log>[Error]: org.python.core.Py.JavaError(Py.java:537)
<Log>[Error]: org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
<Log>[Error]: org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
<Log>[Error]: org.python.core.PyObject.__call__(PyObject.java:478)
<Log>[Error]: org.python.core.PyObject.__call__(PyObject.java:482)
<Log>[Error]: org.python.core.PyMethod.__call__(PyMethod.java:141)
<Log>[Error]: org.python.pycode._pyx80.setupCoreComponentSymbols$13(C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py:190)
<Log>[Error]: org.python.pycode._pyx80.call_function(C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py)
<Log>[Error]: org.python.core.PyTableCode.call(PyTableCode.java:167)
<Log>[Error]: org.python.core.PyBaseCode.call(PyBaseCode.java:124)
<Log>[Error]: org.python.core.PyFunction.__call__(PyFunction.java:403)
<Log>[Error]: org.python.pycode._pyx80.instantiateComponent$14(C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py:350)
<Log>[Error]: org.python.pycode._pyx80.call_function(C:\Users\Maldus\HarmonyFramework\bootloader\config/bootloader.py)
<Log>[Error]: org.python.core.PyTableCode.call(PyTableCode.java:167)
<Log>[Error]: org.python.core.PyBaseCode.call(PyBaseCode.java:138)
<Log>[Error]: org.python.core.PyFunction.__call__(PyFunction.java:413)
<Log>[Error]: org.python.core.PyFunction.__call__(PyFunction.java:408)
<Log>[Error]: com.microchip.h3.database.component.FrameworkComponent.activate(FrameworkComponent.java:334)
<Log>[Error]: com.microchip.h3.database.ComponentManager.activateUniqueComponent(ComponentManager.java:687)
<Log>[Error]: com.microchip.h3.database.ComponentManager.activateComponent(ComponentManager.java:747)
<Log>[Error]: com.microchip.mh3.componentgraph.Graph.handleDragEnd(Graph.java:740)
<Log>[Error]: com.microchip.mh3.componentgraph.Graph.handleEvent(Graph.java:625)
<Log>[Error]: com.microchip.utils.event.EventBus.handleEvent(EventBus.java:257)
<Log>[Error]: com.microchip.utils.event.EventBus.broadcastToHandler(EventBus.java:241)
<Log>[Error]: com.microchip.utils.event.EventBus.broadcastEvents(EventBus.java:206)
<Log>[Error]: com.microchip.utils.event.EventBus.raiseEvent(EventBus.java:131)
<Log>[Error]: com.microchip.mh3.event.Events.raiseEvent(Events.java:76)
<Log>[Error]: com.microchip.mh3.ui.availabletree.AvailableTreeUI$1.mouseReleased(AvailableTreeUI.java:122)
<Log>[Error]: java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
<Log>[Error]: java.awt.Component.processMouseEvent(Component.java:6539)
<Log>[Error]: javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
<Log>[Error]: java.awt.Component.processEvent(Component.java:6304)
<Log>[Error]: java.awt.Container.processEvent(Container.java:2239)
<Log>[Error]: java.awt.Component.dispatchEventImpl(Component.java:4889)
<Log>[Error]: java.awt.Container.dispatchEventImpl(Container.java:2297)
<Log>[Error]: java.awt.Component.dispatchEvent(Component.java:4711)
<Log>[Error]: java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
<Log>[Error]: java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
<Log>[Error]: java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
<Log>[Error]: java.awt.Container.dispatchEventImpl(Container.java:2283)
<Log>[Error]: java.awt.Window.dispatchEventImpl(Window.java:2746)
<Log>[Error]: java.awt.Component.dispatchEvent(Component.java:4711)
<Log>[Error]: java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
<Log>[Error]: java.awt.EventQueue.access$500(EventQueue.java:97)
<Log>[Error]: java.awt.EventQueue$3.run(EventQueue.java:709)
<Log>[Error]: java.awt.EventQueue$3.run(EventQueue.java:703)
<Log>[Error]: java.security.AccessController.doPrivileged(Native Method)
<Log>[Error]: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
<Log>[Error]: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
<Log>[Error]: java.awt.EventQueue$4.run(EventQueue.java:733)
<Log>[Error]: java.awt.EventQueue$4.run(EventQueue.java:731)
<Log>[Error]: java.security.AccessController.doPrivileged(Native Method)
<Log>[Error]: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
<Log>[Error]: java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
<Log>[Error]: org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
<Log>[Error]: java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
<Log>[Error]: java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
<Log>[Error]: java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
<Log>[Error]: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
<Log>[Error]: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
<Log>[Error]: java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I have tried both with my device and other models, to no avail. I am using MPLABX 5.15 and Harmony 3.3.0.1 .

Please kindly confirm whether this library and/or the Harmony framework has been discontinued, if it was ever supposed to work.

**Comment by amitraddi** [comment]
Hi @Maldus512 ,
Bootloader Library in Harmony 3 only supports SAM devices for now. Please refer to below release notes for supported devices. PIC32 will be supported in future releases.
https://github.com/Microchip-MPLAB-Harmony/bootloader/blob/master/release_notes.md

**Comment by Maldus512** [comment]
Thank you for the clarification. 
Still, if the desidered component is unsupported a proper message should be displayed instead of a cryptic Java/Python log printed only with debug level enabled
